#!/usr/bin/env bash
#MISE description="Update mise tools and system packages"

mise self-update -y

if command -v gh &> /dev/null; then
    export GITHUB_TOKEN="$(gh auth token)"
fi

mise up

if command -v claude &> /dev/null; then
    claude update
    claude plugin list --json | jq -r '.[].id' | xargs -n1 claude plugin update
fi

if command -v gh &> /dev/null; then
    gh extension upgrade --all
fi

sudo eix-sync -a
sudo emerge -uDN @world -j2
sudo emerge --depclean
