format = """
$time \
$directory\
$git_branch\
$git_state\
$git_status\
$kubernetes\
$cmd_duration\
$line_break\
$character\
"""

[directory]
truncate_to_repo = false

[time]
disabled = false
format = "[\\[$time\\]]($style)"

[kubernetes]
disabled = false
format = "[$symbol $context (\\($namespace\\))]($style) "
