[tools]

awscli = 'latest'
go = 'latest'
kustomize = 'latest'
nodejs = 'lts'
python = 'latest'
ruby = ['latest', '2.7.1']
rust = 'latest'
terraform = 'latest'
deno = 'latest'
usage = "latest"
bun = "latest"
