[tools]

awscli = 'latest'
go = 'latest'
kustomize = 'latest'
nodejs = 'lts'
python = 'latest'
ruby = ['latest']
rust = 'latest'
terraform = 'latest'
deno = 'latest'
usage = "latest"
bun = "latest"
gcloud = "latest"
stern = "latest"

"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:zenn-cli" = "latest"
"npm:difit" = "latest"
act = "latest"
uv = "latest"
ollama = "latest"

"npm:@openai/codex" = "latest"
